### ISSUE TITLE
Command window empties when searching through tree on Windows

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#115] opened 2022-09-16 11:43 UTC
Wanted to go through hierarchy while writing path for datalad get, but when I opened a folder in the tree, the command window defaulted (and **lost progress on datalad get**).

It may be useful to prevent this for checking paths?

**Comment by mih** [comment] 2022-09-17 12:29
Duplicate of #105 -- this behavior was requested in #57 -- it seems that it is not actually desirable.

**Closed by mih** 2022-09-17 12:29 UTC
