### ISSUE TITLE
Datalad push not pushing much! On Windows

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#119] opened 2022-09-16 12:04 UTC
**To succesfully create github repo from local dataset (i.e. create-sibling-github), only requires a new repo name, credential (i.e. Github username), and a recently generated personal github token.**. <-- These are my notes to remind myself, but might not be intuitive for a first time user?

This works fine, and I like that this sibling is named github, it should help clarify for the GUI users.

### Datalad push does not push _designated path or dataset_ to github-sibling.

Yes, it does push to the sibling, as seen with [repo link](https://github.com/Manukapp/Gooey-Test).
However, **none** of the created datalad dataset and its downloaded subdataset (from OpenNeuro) **are pushed**. Do I need to setup a annex for this to work?

Moreover, action summary displays:
`publish (notneeded: 2)`

**Comment by adswa** [comment] 2022-09-16 14:28
Can't reproduce it on Linux: https://github.com/adswa/gooeytest2

**Comment by adswa** [comment] 2022-09-16 15:23
@all-contributors please add @Manukapp for userTesting

**Comment by mih** [comment] 2022-09-21 06:11
Hard to say what is happening here without more detail. I suspect you tried to push a dataset that had subdatasets. Based on

> However, none of the created datalad dataset and its downloaded subdataset (from OpenNeuro) are pushed

But the dataset at the link you posted has no trace of subdatasets. If that is correct, the observation you made would indicate correct behavior -- not pushing subdatasets that do not exist (or are properly registered).

I am closing this issue, because lots of time has passed and error handling is different now. Feel free to reopen with more information.

**Closed by mih** 2022-09-21 06:11 UTC
Labels: windows
