### ISSUE TITLE
Setting a credential name for create-sibling-gin fails

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#341] opened 2022-10-14 06:26 UTC
I did not have a token configured, but I wanted to have it saved under a specific name once entered. That this not work:

I am *not* asked for a token at all, and it fails with:

```
Running: Dataset('/tmp/myproject').create_sibling_gin(reponame='myprojecttest', private=True, credential='github-mih') create_sibling_gin(error): [unauthorized: None]
```

**Comment by bpoldrack** [comment] 2022-10-14 08:19
Reproduced. Logging reads:

```
[DEBUG  ] FSBrowser has no handler for result from <class 'datalad.distributed.create_sibling_gin.CreateSiblingGin'>
```

**Comment by bpoldrack** [comment] 2022-10-14 09:35
@mih :

Did I get it right, that you do have credentials with that name set up before, just w/o token? If so, how did you achieve that? I can't get `datalad credentials` to list a credential w/o a secret.

**Comment by bpoldrack** [comment] 2022-10-14 10:14
Yes, that's because the widget does not pass on a value that was not in the list of existing choices. However, I'd consider this a somewhat separate issue.

There seems to be several underlying oddities.
1. `datalad credentials` doesn't list all known credentials to begin with. That is: If I set up a credential w/o a secret it's not being shown.
2. If do what @adswa also did (specifying a `brandnew` cred with `Create-sibling-gin`) via CLI, it will ask for a secret the first time. Entering some nonsense fails. But specifying the same creds again will then fail to authenticate w/o ever asking, suggesting it used the nonsense from before. However, those `brandnew` credentials are nowhere to be found (but apparently used).
3. Via CLI and such a call as in 2., I end up in datalad core's `_set_request_header` of `create_sibling_ghlike`, while it's supposed to be the patched version from datalad-next.

**Comment by bpoldrack** [comment] 2022-10-14 14:08
I think most of the confusing mess described above is going to be addressed by https://github.com/datalad/datalad-next/pull/114

**Comment by adswa** [comment] 2023-04-20 13:50
Since the linked PR was merged, I have given this another try, and I can't reproduce the problem anymore. A not-yet-known credential name causes an interactive query in a Dialog window, and it will successfully save this credential if it worked. Closing.

**Closed by adswa** 2023-04-20 13:50 UTC
